import { BaseResource } from './base-resource';

/** A message in an OpenAI-compatible chat completion request or response. */
export interface ChatCompletionMessage {
  /** The role of the message author (e.g. `"system"`, `"user"`, `"assistant"`). */
  role: string;
  /** The message text content. */
  content: string;
}

/**
 * Input for creating a chat completion. Follows the OpenAI chat completions
 * API format. Additional OpenAI-compatible fields (e.g. `tools`, `max_tokens`)
 * can be passed as extra properties via the index signature.
 */
export interface ChatCompletionRequest {
  /** The model ID to use (e.g. `"gpt-4o"`, `"claude-3-opus"`). */
  model: string;
  /** The conversation messages. */
  messages: ChatCompletionMessage[];
  /** Sampling temperature (0-2). Lower values are more deterministic. */
  temperature?: number;
  /** Nucleus sampling parameter (0-1). */
  top_p?: number;
  /** Whether to stream the response. Note: the SDK does not currently return a stream. */
  stream?: boolean;
  /** Additional OpenAI-compatible parameters are passed through. */
  [key: string]: unknown;
}

/** A single completion choice returned by the model. */
export interface ChatCompletionChoice {
  /** The index of this choice in the choices array. */
  index: number;
  /** The model's response message. */
  message: ChatCompletionMessage;
  /** The reason the model stopped generating (e.g. `"stop"`, `"length"`). */
  finish_reason: string | null;
}

/** Token usage statistics for a chat completion request. */
export interface ChatCompletionUsage {
  /** Number of tokens in the prompt / input messages. */
  prompt_tokens: number;
  /** Number of tokens generated by the model. */
  completion_tokens: number;
  /** Total tokens used (prompt + completion). */
  total_tokens: number;
}

/** Response from an OpenAI-compatible chat completion. */
export interface ChatCompletionResponse {
  /** Unique identifier for this completion. */
  id: string;
  /** Object type (always `"chat.completion"`). */
  object: string;
  /** Unix timestamp (seconds) when the completion was created. */
  created: number;
  /** The model that generated the completion. */
  model: string;
  /** The generated completion choices. Typically contains one choice. */
  choices: ChatCompletionChoice[];
  /** Token usage statistics. May be absent in streamed responses. */
  usage?: ChatCompletionUsage;
}

/** An AI model available through the Gigadrive AI Gateway. */
export interface AiModel {
  /** The model identifier (e.g. `"gpt-4o"`, `"claude-3-opus"`). */
  id: string;
  /** Object type (always `"model"`). */
  object: string;
  /** Unix timestamp (seconds) when the model was created/registered. */
  created?: number;
  /** The organization or provider that owns the model. */
  owned_by?: string;
}

/** Response from listing available AI models. */
export interface AiModelList {
  /** Object type (always `"list"`). */
  object: string;
  /** The available models. */
  data: AiModel[];
}

/**
 * Interact with the Gigadrive AI Gateway — an OpenAI-compatible API that
 * routes requests to multiple AI providers. Accessed via
 * {@link GigadriveClient.aiGateway}.
 *
 * @example
 * ```ts
 * // Chat completion
 * const response = await client.aiGateway.chatCompletions({
 *   model: 'gpt-4o',
 *   messages: [
 *     { role: 'system', content: 'You are a helpful assistant.' },
 *     { role: 'user', content: 'What is the capital of France?' },
 *   ],
 * });
 * console.log(response.choices[0].message.content);
 *
 * // List available models
 * const { data: models } = await client.aiGateway.listModels();
 * console.log(models.map((m) => m.id));
 * ```
 */
export class AiGatewayResource extends BaseResource {
  /**
   * Create a chat completion using the OpenAI-compatible endpoint. Supports
   * all standard OpenAI parameters (temperature, tools, max_tokens, etc.).
   *
   * Requires the `network:ai_gateway:chat` scope.
   *
   * @param data - The chat completion request (model, messages, and optional parameters).
   * @returns The completion response with generated message(s) and usage stats.
   *
   * @example
   * ```ts
   * const response = await client.aiGateway.chatCompletions({
   *   model: 'gpt-4o',
   *   messages: [{ role: 'user', content: 'Hello!' }],
   *   temperature: 0.7,
   * });
   *
   * const reply = response.choices[0].message.content;
   * console.log(`Tokens used: ${response.usage?.total_tokens}`);
   * ```
   */
  async chatCompletions(data: ChatCompletionRequest): Promise<ChatCompletionResponse> {
    return this.httpClient.post('/v1/chat/completions', data);
  }

  /**
   * List all AI models available through the gateway.
   *
   * Requires the `network:ai_gateway:models` scope.
   *
   * @returns An object containing the list of available models.
   *
   * @example
   * ```ts
   * const { data: models } = await client.aiGateway.listModels();
   * for (const model of models) {
   *   console.log(`${model.id} (by ${model.owned_by})`);
   * }
   * ```
   */
  async listModels(): Promise<AiModelList> {
    return this.httpClient.get('/v1/models');
  }

  /**
   * Get details for a specific AI model by its ID.
   *
   * @param modelId - The model identifier (e.g. `"gpt-4o"`).
   * @returns The model details.
   *
   * @example
   * ```ts
   * const model = await client.aiGateway.getModel('gpt-4o');
   * console.log(`${model.id}, owned by ${model.owned_by}`);
   * ```
   */
  async getModel(modelId: string): Promise<AiModel> {
    return this.httpClient.get(`/v1/models/${modelId}`);
  }
}
