// ---------------------------------------------------------------------------
// dotenv serialization helpers
//
// Pure functions (no I/O) for turning key/value pairs into `.env` file contents
// and reading a few values back. Kept dependency-free so they are trivially unit
// testable and can be reused by both `env pull` and `setup`.
// ---------------------------------------------------------------------------

/** A single environment entry to serialize. */
export interface EnvEntry {
  key: string;
  value: string;
}

/** Default header written at the top of a generated `.env` file. */
export const DEFAULT_ENV_HEADER = '# Generated by `gigadrive env pull` — do not edit by hand.';

// Values matching this are safe to emit unquoted; anything else is double-quoted.
const UNQUOTED_SAFE = /^[A-Za-z0-9_.\-/@:+]*$/;

/**
 * Format a single value for a `.env` file. Identifier-like values (and the empty
 * string) are emitted verbatim; anything containing whitespace, quotes, `#`,
 * `=`, or control characters is double-quoted with escapes that standard dotenv
 * parsers reverse — so values round-trip.
 */
export const formatEnvValue = (value: string): string => {
  if (UNQUOTED_SAFE.test(value)) {
    return value;
  }
  const escaped = value
    .replace(/\\/g, '\\\\')
    .replace(/"/g, '\\"')
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\t/g, '\\t');
  return `"${escaped}"`;
};

/**
 * Serialize env entries into `.env` file contents with a leading header comment.
 * Entry order is preserved.
 */
export const serializeEnv = (entries: ReadonlyArray<EnvEntry>, opts?: { header?: string }): string => {
  const header = opts?.header ?? DEFAULT_ENV_HEADER;
  if (entries.length === 0) {
    return `${header}\n`;
  }
  const body = entries.map((e) => `${e.key}=${formatEnvValue(e.value)}`).join('\n');
  return `${header}\n${body}\n`;
};

/**
 * Parse `.env` file contents into a key→value map. Handles unquoted values and
 * double-quoted values with standard escapes; comment (`#`) and blank lines are
 * ignored. Intended for recovering a few known keys (e.g. `GIGADRIVE_CLIENT_ID`),
 * not as a full-fidelity dotenv parser.
 */
export const parseEnv = (content: string): Record<string, string> => {
  const result: Record<string, string> = {};
  for (const rawLine of content.split('\n')) {
    const line = rawLine.trim();
    if (line.length === 0 || line.startsWith('#')) {
      continue;
    }
    const eq = line.indexOf('=');
    if (eq <= 0) {
      continue;
    }
    const key = line.slice(0, eq).trim();
    let value = line.slice(eq + 1).trim();
    if (value.length >= 2 && value.startsWith('"') && value.endsWith('"')) {
      // Single-pass decode: consume each backslash together with the character it
      // escapes, left to right. A sequential chain of `.replace()` calls would
      // mis-handle a literal backslash followed by n/r/t/" (e.g. `C:\\new` after
      // escaping would decode `\n` before collapsing `\\`).
      value = value.slice(1, -1).replace(/\\(\\|"|n|r|t)/g, (_, ch: string) => {
        switch (ch) {
          case 'n':
            return '\n';
          case 'r':
            return '\r';
          case 't':
            return '\t';
          case '"':
            return '"';
          default:
            return '\\';
        }
      });
    }
    result[key] = value;
  }
  return result;
};
